server:
  port: 8081
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/fitness_user_db
      username: postgres
      password: hi123

  jpa:
      hibernate:
          ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
